import { Stack } from "aws-cdk-lib";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import * as ssm from "aws-cdk-lib/aws-ssm";
import { Construct } from "constructs";

/* ============================================================
   Where configuration comes from.

   Two stores, split on one line: whether reading the value is
   harmful.

   Ordinary config — origins, the default short domain, log
   level, throttle limits — lives in **SSM Parameter Store**.
   Standard parameters are free at any volume this project will
   ever reach, which is why docs/DECISIONS.md chose it over
   Secrets Manager for config in the first place.

   Secrets — the database password and the two JWT signing keys
   — live in **Secrets Manager**, generated by CloudFormation so
   that no human ever chooses them and no value is ever typed
   into this repository.

   Neither is baked into a container image: the images are built
   from the repository alone and contain no configuration at all,
   so the same image is deployable to any stage.

   Config (SSM) vs secrets (Secrets Manager), resolved differently:

   Ordinary config is read at *deploy* time, by CloudFormation,
   and lands in the Lambda's environment as-is. Reading it is
   harmless, so there is no reason to defer it.

   The two JWT signing keys and the database password are handled
   by issue #292, now IMPLEMENTED. Originally they too were read
   at deploy time via `unsafeUnwrap()`, which writes their
   plaintext into the synthesized CloudFormation template — copies
   of every secret in the CDK assets bucket and in CloudFormation's
   stack history, not just in the Lambda environment. The reason
   given for accepting that was cost: the app Lambdas sat in
   isolated subnets with no NAT, so a runtime Secrets Manager
   lookup needed an interface VPC endpoint at ~$7/month, and the
   only reader of a Lambda's configuration was the account owner.

   Both halves of that trade changed. natStrategy now defaults to a
   NAT instance (see snapurl-stack.ts), so the app Lambdas have
   egress and reach Secrets Manager at runtime with no dedicated
   endpoint — the $7/month is gone. And under the open-source
   framing every operator is a different account with its own IAM
   discipline, so "the account owner is the only reader" is not an
   assumption to make on their behalf. So on the egress profiles
   ('instance'/'gateway') the stack now passes Secrets Manager
   *ARNs* into the environment and each function resolves the
   secret(s) it needs at cold start, caching the result for the
   life of the execution environment (a warm invocation pays
   nothing). Per-function IAM grants restrict each function to only
   the secrets it reads. No `unsafeUnwrap()` runs on these paths,
   so no secret value reaches the template.

   Two escape hatches keep the other profiles working. natStrategy
   'none' is isolated with no egress, so a runtime lookup would
   hang; there the deploy-time `unsafeUnwrap()` is preserved and the
   plaintext-in-template tradeoff is accepted for that zero-cost
   choice. And the single-node / Kubernetes profiles have no Secrets
   Manager at all: the app-side resolver falls back to a plain
   DATABASE_URL / JWT_* env var whenever the matching *_SECRET_ARN
   is absent.

   What deploy-time resolution costs, on the profiles that still use
   it: rotating a value takes a redeploy rather than taking effect
   on the next cold start. For a signing key that is the right shape
   anyway — rotating one invalidates every token in flight, so it is
   a deliberate operation, not a background one.
   ============================================================ */

/** Parameters the stack reads. The names are the suffix under `prefix`. */
export const CONFIG_KEYS = [
  "web-origin",
  "redirect-origin",
  "default-domain",
  "log-level",
  "mail-from",
  "mail-transport",
  "throttle-limit",
  "throttle-ttl-seconds",
] as const;

export type ConfigKey = (typeof CONFIG_KEYS)[number];

export interface SnapUrlConfigProps {
  /** Parameter Store prefix, e.g. `/snapurl/prod`. No trailing slash. */
  readonly prefix: string;
}

export class SnapUrlConfig extends Construct {
  private readonly prefix: string;
  private readonly values = new Map<ConfigKey, string>();

  /** Generated at deploy time, never chosen by a human, never in this repo. */
  readonly jwtAccessSecret: secretsmanager.Secret;
  readonly jwtRefreshSecret: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props: SnapUrlConfigProps) {
    super(scope, id);
    this.prefix = props.prefix.replace(/\/$/, "");

    /* Two separate keys, deliberately. apps/api/src/config/env.ts explains
       why: if one key signed both tokens, a stolen access token could be
       replayed as a refresh token and never expire. Two secrets is therefore
       a requirement, not an oversight — and at $0.40/secret/month it is about
       5% of what the database costs.

       No punctuation: these end up in environment variables and in a URL-safe
       JWT signature path, and an unlucky quote character in a generated value
       is a class of deploy failure that is miserable to diagnose. 64
       alphanumeric characters is ~380 bits, well past the 32-character floor
       the schema enforces. */
    const generate = { passwordLength: 64, excludePunctuation: true, includeSpace: false };

    this.jwtAccessSecret = new secretsmanager.Secret(this, "JwtAccess", {
      description: "SnapURL JWT access-token signing key. Generated; rotating it logs everyone out.",
      generateSecretString: generate,
    });
    this.jwtRefreshSecret = new secretsmanager.Secret(this, "JwtRefresh", {
      description: "SnapURL JWT refresh-token signing key. Must differ from the access key.",
      generateSecretString: generate,
    });
  }

  /**
   * Read one parameter.
   *
   * There is deliberately no default. A default here would be a second copy of
   * a value the application already defaults for itself in
   * `apps/api/src/config/env.ts`, and the two would drift. Instead a missing
   * parameter fails the deploy naming the parameter, which is a better time to
   * find out than the first request.
   *
   * `infra/bin/put-parameters.sh` creates all of them in one command.
   */
  get(key: ConfigKey): string {
    const cached = this.values.get(key);
    if (cached) return cached;
    const value = ssm.StringParameter.valueForStringParameter(
      Stack.of(this),
      `${this.prefix}/${key}`,
    );
    this.values.set(key, value);
    return value;
  }

  /** The full parameter path, for error messages and outputs. */
  path(key: ConfigKey): string {
    return `${this.prefix}/${key}`;
  }
}
