import path from "node:path";
import { defineConfig, devices } from "@playwright/test";

/* ============================================================
   Journeys config — 12 full user-journey E2E specs against the REAL stack.

   Unlike playwright.real.config.ts (which re-runs the fixtures specs against
   the real backend), this config has its own spec directory (e2e/journeys/)
   written from scratch per the rules in brief-journey.md:
     - No hardcoded ids/slugs/URLs generated by the app
     - No fixture-shaped assertions
     - Every identity derived per run (no fixed emails)
     - Oracle: packages/contract (zod schemas), docs/, observed behaviour

   Requires a running staging stack: api :3001, redirect :3002, postgres :5435.
   The web app (Next.js) is built and served here on port 3000.

   Raw artifacts (.qa-runs/journeys/) are gitignored.
   ============================================================ */

const PORT = Number(process.env.QA_WEB_PORT ?? 3000);
const BASE_URL = `http://localhost:${PORT}`;
const API_URL = process.env.QA_API_URL ?? "http://localhost:3001/api/v1";
const REDIRECT_URL = process.env.QA_REDIRECT_URL ?? "http://localhost:3002";

export const JOURNEYS_API_URL = API_URL;
export const JOURNEYS_REDIRECT_URL = REDIRECT_URL;

const RUN_DIR = process.env.QA_RUN_DIR ?? path.resolve(__dirname, "../.qa-runs/journeys");
const ARTIFACTS = path.join(RUN_DIR, "artifacts");

export default defineConfig({
  testDir: "./journeys",
  fullyParallel: false,    // journeys share the web server build; run sequentially
  forbidOnly: !!process.env.CI,
  retries: 0,              // no retries — failures are findings
  workers: 1,
  reporter: [
    ["list"],
    ["json", { outputFile: path.join(ARTIFACTS, "journeys.json") }],
    ["html", { outputFolder: path.join(ARTIFACTS, "html"), open: "never" }],
  ],
  outputDir: path.join(ARTIFACTS, "test-results"),
  timeout: 60_000,         // journeys are longer than single-surface specs
  expect: { timeout: 15_000 },
  use: {
    baseURL: BASE_URL,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },
  projects: [
    {
      name: "desktop",
      use: { ...devices["Desktop Chrome"], viewport: { width: 1280, height: 800 } },
    },
    {
      name: "mobile",
      use: { ...devices["Pixel 5"], viewport: { width: 390, height: 844 } },
      /* Only journeys with a meaningful mobile surface run on mobile;
         the spec files opt in with a tag or the grep below. */
      grep: /@mobile/,
    },
  ],
  webServer: {
    /* The app was already built; only `next start` is needed here.
       Playwright starts this command and waits for the URL to respond.
       reuseExistingServer: false ensures we never reuse the fixtures build
       that might be running on the same port. */
    command: `NEXT_PUBLIC_USE_FIXTURES=false NEXT_PUBLIC_API_URL=${API_URL} SNAPURL_ALLOW_UNCONFIGURED_BUILD=true pnpm --filter snapurl-web exec next start --port ${PORT}`,
    url: BASE_URL,
    reuseExistingServer: false,
    timeout: 60_000,
    env: {
      NEXT_PUBLIC_USE_FIXTURES: "false",
      NEXT_PUBLIC_API_URL: API_URL,
      SNAPURL_ALLOW_UNCONFIGURED_BUILD: "true",
    },
  },
});
